#ifndef MEMBERSHIPMANAGERS_MMBASE_MMBASE_H_
#define MEMBERSHIPMANAGERS_MMBASE_MMBASE_H_

class MMBase {
public:
    MMBase();
    virtual ~MMBase();
};

#endif /* MEMBERSHIPMANAGERS_MMBASE_MMBASE_H_ */
